# Generated by Django 3.2.5 on 2021-07-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to='images', verbose_name='path'),
        ),
    ]
