# Generated by Django 3.2.5 on 2021-07-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_alter_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
