# Generated by Django 3.2.5 on 2021-07-29 04:04

import apps.image.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_alter_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 't1'), (1, 't2')], default=0, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.FileField(upload_to=apps.image.models.get_upload_path),
        ),
    ]
