# Generated by Django 3.2.5 on 2021-07-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20210729_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 't1'), (2, 't2')], default=1, verbose_name='type'),
        ),
    ]
