# Generated by Django 3.2.5 on 2021-07-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='status',
        ),
        migrations.AddField(
            model_name='model',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
